// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TravelTourManagement.DataAccess.Context;
using TravelTourManagement.DataAccess.Enums;

#nullable disable

namespace TravelTourManagement.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260604070130_AddWishlistFeature")]
    partial class AddWishlistFeature
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "booking_status", new[] { "pending", "confirmed", "cancelled", "completed", "refunded" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "day_session", "day_session", new[] { "morning", "afternoon", "evening", "full_day" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "document_status", new[] { "uploaded", "verified", "rejected" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "inclusion_type", "inclusion_type", new[] { "included", "excluded", "optional" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "meal_type", "meal_type", new[] { "breakfast", "lunch", "dinner", "all_inclusive", "none" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "media_category", "media_category", new[] { "hotel", "transport", "food", "destination", "activity", "cover" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "message_sender_role", new[] { "user", "packager" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "notification_type", new[] { "booking", "payment", "review", "approval", "system", "message" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "package_status", "package_status", new[] { "draft", "pending_review", "published", "archived", "completed" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "package_type", "package_type", new[] { "group", "private", "honeymoon", "family", "adventure", "pilgrimage" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "packager_status", new[] { "pending", "approved", "suspended", "deactivated" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "payment_status", new[] { "unpaid", "partial", "paid", "refunded", "failed" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "review_status", new[] { "pending", "published", "flagged", "removed" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "transport_mode", "transport_mode", new[] { "bus", "train", "flight", "car", "boat", "van", "walk", "other" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "user_role", new[] { "user", "admin", "packager" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("booking_ref_seq");

            modelBuilder.Entity("TravelTourManagement.DataAccess.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ip_address");

                    b.Property<string>("NewValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("new_values");

                    b.Property<string>("OldValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("old_values");

                    b.Property<DateTime>("PerformedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("performed_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("PerformedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("performed_by");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_agent");

                    b.HasKey("Id")
                        .HasName("audit_logs_pkey");

                    b.HasIndex(new[] { "Action" }, "idx_audit_action");

                    b.HasIndex(new[] { "EntityType", "EntityId" }, "idx_audit_entity");

                    b.HasIndex(new[] { "PerformedAt" }, "idx_audit_performed_at")
                        .IsDescending();

                    b.HasIndex(new[] { "PerformedBy" }, "idx_audit_performed_by");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("TravelTourManagement.DataAccess.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<int>("AdultCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("adult_count");

                    b.Property<DateTime>("BookedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("booked_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("BookingReference")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("booking_reference");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("text")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<int>("ChildCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("child_count");

                    b.Property<int>("InfantCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("infant_count");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uuid")
                        .HasColumnName("package_id");

                    b.Property<decimal>("PackagerBaseAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("packager_base_amount");

                    b.Property<decimal>("PaidAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("paid_amount");

                    b.Property<PaymentStatus>("PaymentStatus")
                        .HasColumnType("payment_status")
                        .HasColumnName("payment_status");

                    b.Property<decimal>("PlatformFeeAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("platform_fee_amount");

                    b.Property<decimal>("PlatformFeePercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("platform_fee_percent");

                    b.Property<DateOnly>("ReturnDate")
                        .HasColumnType("date")
                        .HasColumnName("return_date");

                    b.Property<Guid>("SeasonalPricingId")
                        .HasColumnType("uuid")
                        .HasColumnName("seasonal_pricing_id");

                    b.Property<string>("SpecialRequests")
                        .HasColumnType("text")
                        .HasColumnName("special_requests");

                    b.Property<BookingStatus>("Status")
                        .HasColumnType("booking_status")
                        .HasColumnName("status");

                    b.Property<decimal>("TaxAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("tax_amount");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total_amount");

                    b.Property<DateOnly>("TravelDate")
                        .HasColumnType("date")
                        .HasColumnName("travel_date");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("bookings_pkey");

                    b.HasIndex("SeasonalPricingId");

                    b.HasIndex(new[] { "BookingReference" }, "bookings_booking_reference_key")
                        .IsUnique();

                    b.HasIndex(new[] { "PackageId" }, "idx_bookings_package_id");

                    b.HasIndex(new[] { "BookingReference" }, "idx_bookings_reference");

                    b.HasIndex(new[] { "TravelDate" }, "idx_bookings_travel_date");

                    b.HasIndex(new[] { "UserId" }, "idx_bookings_user_id");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("TravelTourManagement.DataAccess.Entities.BookingTraveler", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("AadharCardNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("aadhar_card_number");

                    b.Property<int?>("Age")
                        .HasColumnType("integer")
                        .HasColumnName("age");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("full_name");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("gender");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_primary");

                    b.Property<string>("MealPreference")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("meal_preference");

                    b.Property<string>("Nationality")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nationality");

                    b.Property<string>("PassportNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("passport_number");

                    b.HasKey("Id")
                        .HasName("booking_travelers_pkey");

                    b.HasIndex(new[] { "BookingId" }, "idx_travelers_booking_id");

                    b.ToTable("booking_travelers", (string)null);
                });

            modelBuilder.Entity("TravelTourManagement.DataAccess.Entities.ItineraryActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("ActivityTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("activity_title");

                    b.Property<string>("ActivityType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("activity_type");

                    b.Property<DaySession>("DaySession")
                        .HasColumnType("day_session")
                        .HasColumnName("session");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<decimal>("ExtraCost")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("extra_cost");

                    b.Property<bool>("IsOptional")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_optional");

                    b.Property<Guid>("ItineraryDayId")
                        .HasColumnType("uuid")
                        .HasColumnName("itinerary_day_id");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("location");

                    b.Property<int>("SequenceOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("sequence_order");

                    b.HasKey("Id")
                        .HasName("itinerary_activities_pkey");

                    b.HasIndex(new[] { "ItineraryDayId" }, "idx_activities_day_id");

                    b.ToTable("itinerary_activities", (string)null);
                });

            modelBuilder.Entity("TravelTourManagement.DataAccess.Entities.ItineraryDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("DayNumber")
                        .HasColumnType("integer")
                        .HasColumnName("day_number");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("location");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uuid")
                        .HasColumnName("package_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("itinerary_days_pkey");

                    b.HasIndex(new[] { "PackageId" }, "idx_itinerary_days_package_id");

                    b.HasIndex(new[] { "PackageId", "DayNumber" }, "uq_itinerary_day")
                        .IsUnique();

                    b.ToTable("itinerary_days", (string)null);
                });

            modelBuilder.Entity("TravelTourManagement.DataAccess.Entities.ItineraryDayMeal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("description");

                    b.Property<bool>("IsIncluded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_included");

                    b.Property<Guid>("ItineraryDayId")
                        .HasColumnType("uuid")
                        .HasColumnName("itinerary_day_id");

                    b.Property<MealType>("MealType")
                        .HasColumnType("meal_type")
                        .HasColumnName("meal");

                    b.Property<string>("Venue")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("venue");

                    b.HasKey("Id")
                        .HasName("itinerary_day_meals_pkey");

                    b.HasIndex(new[] { "ItineraryDayId" }, "idx_meals_day_id");

                    b.ToTable("itinerary_day_meals", (string)null);
                });

            modelBuilder.Entity("TravelTourManagement.DataAccess.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_id");

                    b.Property<DateTime>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("sent_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ThreadId")
                        .HasColumnType("uuid")
                        .HasColumnName("thread_id");

                    b.HasKey("Id")
                        .HasName("messages_pkey");

                    b.HasIndex(new[] { "SenderId" }, "idx_messages_sender_id");

                    b.HasIndex(new[] { "ThreadId" }, "idx_messages_thread_id");

                    b.HasIndex(new[] { "ThreadId", "IsRead" }, "idx_messages_unread")
                        .HasFilter("(is_read = false)");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("TravelTourManagement.DataAccess.Entities.MessageThread", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("LastMessageAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_message_at");

                    b.Property<Guid?>("PackageId")
                        .HasColumnType("uuid")
                        .HasColumnName("package_id");

                    b.Property<Guid>("PackagerId")
                        .HasColumnType("uuid")
                        .HasColumnName("packager_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("message_threads_pkey");

                    b.HasIndex(new[] { "PackageId" }, "idx_threads_package_id");

                    b.HasIndex(new[] { "PackagerId" }, "idx_threads_packager_id");

                    b.HasIndex(new[] { "UserId" }, "idx_threads_user_id");

                    b.HasIndex(new[] { "UserId", "PackagerId", "PackageId" }, "uq_thread")
                        .IsUnique();

                    b.ToTable("message_threads", (string)null);
                });

            modelBuilder.Entity("TravelTourManagement.DataAccess.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("reference_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("notifications_pkey");

                    b.HasIndex(new[] { "UserId", "IsRead" }, "idx_notifications_unread")
                        .HasFilter("(is_read = false)");

                    b.HasIndex(new[] { "UserId" }, "idx_notifications_user_id");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("TravelTourManagement.DataAccess.Entities.Package", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<decimal>("AvgRating")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("avg_rating")
                        .HasDefaultValueSql("0.00");

                    b.Property<string>("CancellationPolicy")
                        .HasColumnType("text")
                        .HasColumnName("cancellation_policy");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CurrentBookings")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("current_bookings");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("destination");

                    b.Property<int>("DurationDays")
                        .HasColumnType("integer")
                        .HasColumnName("duration_days");

                    b.Property<int>("DurationNights")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("duration_nights");

                    b.Property<bool>("IsFeatured")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_featured");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("integer")
                        .HasColumnName("max_capacity");

                    b.Property<int?>("MinAge")
                        .HasColumnType("integer")
                        .HasColumnName("min_age");

                    b.Property<Guid>("PackagerId")
                        .HasColumnType("uuid")
                        .HasColumnName("packager_id");

                    b.Property<PackageStatus>("Status")
                        .HasColumnType("package_status")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<int>("TotalReviews")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_reviews");

                    b.Property<PackageType>("Type")
                        .HasColumnType("package_type")
                        .HasColumnName("package_type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("packages_pkey");

                    b.HasIndex(new[] { "Country" }, "idx_packages_country");

                    b.HasIndex(new[] { "Destination" }, "idx_packages_dest_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "Destination" }, "idx_packages_dest_trgm"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex(new[] { "Destination" }, "idx_packages_dest_trgm"), new[] { "gin_trgm_ops" });

                    b.HasIndex(new[] { "Destination" }, "idx_packages_destination");

                    b.HasIndex(new[] { "IsFeatured" }, "idx_packages_featured")
                        .HasFilter("(is_featured = true)");

                    b.HasIndex(new[] { "PackagerId" }, "idx_packages_packager_id");

                    b.HasIndex(new[] { "AvgRating" }, "idx_packages_rating")
                        .IsDescending();

                    b.HasIndex(new[] { "Title" }, "idx_packages_title_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "Title" }, "idx_packages_title_trgm"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex(new[] { "Title" }, "idx_packages_title_trgm"), new[] { "gin_trgm_ops" });

                    b.ToTable("packages", (string)null);
                });

            modelBuilder.Entity("TravelTourManagement.DataAccess.Entities.PackageAccommodation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Amenities")
                        .HasColumnType("text")
                        .HasColumnName("amenities");

                    b.Property<TimeOnly?>("CheckInTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("check_in_time");

                    b.Property<TimeOnly?>("CheckOutTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("check_out_time");

                    b.Property<string>("HotelAddress")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("hotel_address");

                    b.Property<string>("HotelName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("hotel_name");

                    b.Property<Guid>("ItineraryDayId")
                        .HasColumnType("uuid")
                        .HasColumnName("itinerary_day_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("RoomType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("room_type");

                    b.Property<short?>("StarRating")
                        .HasColumnType("smallint")
                        .HasColumnName("star_rating");

                    b.HasKey("Id")
                        .HasName("package_accommodation_pkey");

                    b.HasIndex(new[] { "ItineraryDayId" }, "idx_accommodation_day_id");

                    b.ToTable("package_accommodation", (string)null);
                });

            modelBuilder.Entity("TravelTourManagement.DataAccess.Entities.PackageHighlight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<string>("HighlightText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("highlight_text");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uuid")
                        .HasColumnName("package_id");

                    b.HasKey("Id")
                        .HasName("package_highlights_pkey");

                    b.HasIndex(new[] { "PackageId" }, "idx_highlights_package_id");

                    b.ToTable("package_highlights", (string)null);
                });

            modelBuilder.Entity("TravelTourManagement.DataAccess.Entities.PackageInclusion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uuid")
                        .HasColumnName("package_id");

                    b.Property<InclusionType>("Type")
                        .HasColumnType("inclusion_type")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("package_inclusions_pkey");

                    b.HasIndex(new[] { "PackageId" }, "idx_inclusions_package_id");

                    b.ToTable("package_inclusions", (string)null);
                });

            modelBuilder.Entity("TravelTourManagement.DataAccess.Entities.PackageMedium", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Caption")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("caption");

                    b.Property<MediaCategory>("Category")
                        .HasColumnType("media_category")
                        .HasColumnName("category");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_path");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_primary");

                    b.Property<string>("MimeType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("mime_type");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uuid")
                        .HasColumnName("package_id");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("uploaded_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("package_media_pkey");

                    b.HasIndex(new[] { "PackageId" }, "idx_media_package_id");

                    b.HasIndex(new[] { "PackageId", "IsPrimary" }, "idx_media_primary")
                        .HasFilter("(is_primary = true)");

                    b.ToTable("package_media", (string)null);
                });

            modelBuilder.Entity("TravelTourManagement.DataAccess.Entities.PackageSeasonalPricing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<int>("AvailableSlots")
                        .HasColumnType("integer")
                        .HasColumnName("available_slots");

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("base_price");

                    b.Property<decimal>("ChildPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("child_price");

                    b.Property<decimal>("DiscountPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("discount_percent");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uuid")
                        .HasColumnName("package_id");

                    b.Property<string>("SeasonName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("season_name");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("Id")
                        .HasName("package_seasonal_pricing_pkey");

                    b.HasIndex(new[] { "IsActive" }, "idx_pricing_active")
                        .HasFilter("(is_active = true)");

                    b.HasIndex(new[] { "StartDate", "EndDate" }, "idx_pricing_dates");

                    b.HasIndex(new[] { "PackageId" }, "idx_pricing_package_id");

                    b.ToTable("package_seasonal_pricing", (string)null);
                });

            modelBuilder.Entity("TravelTourManagement.DataAccess.Entities.PackageTransport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<decimal?>("DistanceKm")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("distance_km");

                    b.Property<string>("DropPoint")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("drop_point");

                    b.Property<TimeOnly?>("DropTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("drop_time");

                    b.Property<Guid>("ItineraryDayId")
                        .HasColumnType("uuid")
                        .HasColumnName("itinerary_day_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("PickupPoint")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("pickup_point");

                    b.Property<TimeOnly?>("PickupTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("pickup_time");

                    b.Property<int>("SegmentOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("segment_order");

                    b.Property<TransportMode>("TransportMode")
                        .HasColumnType("transport_mode")
                        .HasColumnName("mode");

                    b.Property<string>("VehicleDescription")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("vehicle_description");

                    b.HasKey("Id")
                        .HasName("package_transport_pkey");

                    b.HasIndex(new[] { "ItineraryDayId" }, "idx_transport_day_id");

                    b.ToTable("package_transport", (string)null);
                });

            modelBuilder.Entity("TravelTourManagement.DataAccess.Entities.Packager", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by");

                    b.Property<decimal>("AvgRating")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("avg_rating")
                        .HasDefaultValueSql("0.00");

                    b.Property<string>("BusinessLicenseNo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("business_license_no");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("company_name");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("contact_phone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deactivated_at");

                    b.Property<string>("DeactivationReason")
                        .HasColumnType("text")
                        .HasColumnName("deactivation_reason");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("TotalReviews")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_reviews");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("website_url");

                    b.HasKey("Id")
                        .HasName("packagers_pkey");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex(new[] { "AvgRating" }, "idx_packagers_rating")
                        .IsDescending();

                    b.HasIndex(new[] { "UserId" }, "idx_packagers_user_id");

                    b.HasIndex(new[] { "UserId" }, "packagers_user_id_key")
                        .IsUnique();

                    b.ToTable("packagers", (string)null);
                });

            modelBuilder.Entity("TravelTourManagement.DataAccess.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("currency")
                        .HasDefaultValueSql("'INR'::character varying");

                    b.Property<string>("GatewayResponse")
                        .HasColumnType("text")
                        .HasColumnName("gateway_response");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("paid_at");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("payment_method");

                    b.Property<decimal?>("RefundAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("refund_amount")
                        .HasDefaultValueSql("0");

                    b.Property<DateTime?>("RefundedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("refunded_at");

                    b.Property<PaymentStatus>("Status")
                        .HasColumnType("payment_status")
                        .HasColumnName("status");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("transaction_id");

                    b.HasKey("Id")
                        .HasName("payments_pkey");

                    b.HasIndex(new[] { "BookingId" }, "idx_payments_booking_id");

                    b.HasIndex(new[] { "PaidAt" }, "idx_payments_paid_at");

                    b.HasIndex(new[] { "TransactionId" }, "payments_transaction_id_key")
                        .IsUnique();

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("TravelTourManagement.DataAccess.Entities.PlatformConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<decimal>("GstPercent")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("gst_percent")
                        .HasDefaultValueSql("18.00");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<decimal>("PlatformFeePercent")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("platform_fee_percent")
                        .HasDefaultValueSql("5.00");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("platform_config_pkey");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("platform_config", (string)null);
                });

            modelBuilder.Entity("TravelTourManagement.DataAccess.Entities.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<short?>("AccommodationRating")
                        .HasColumnType("smallint")
                        .HasColumnName("accommodation_rating");

                    b.Property<string>("AdminNote")
                        .HasColumnType("text")
                        .HasColumnName("admin_note");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<short?>("FoodRating")
                        .HasColumnType("smallint")
                        .HasColumnName("food_rating");

                    b.Property<short?>("GuideRating")
                        .HasColumnType("smallint")
                        .HasColumnName("guide_rating");

                    b.Property<bool>("IsVerifiedTraveler")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_verified_traveler");

                    b.Property<short>("OverallRating")
                        .HasColumnType("smallint")
                        .HasColumnName("overall_rating");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uuid")
                        .HasColumnName("package_id");

                    b.Property<Guid>("PackagerId")
                        .HasColumnType("uuid")
                        .HasColumnName("packager_id");

                    b.Property<short?>("TransportRating")
                        .HasColumnType("smallint")
                        .HasColumnName("transport_rating");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<short?>("ValueRating")
                        .HasColumnType("smallint")
                        .HasColumnName("value_rating");

                    b.HasKey("Id")
                        .HasName("reviews_pkey");

                    b.HasIndex(new[] { "OverallRating" }, "idx_reviews_overall")
                        .IsDescending();

                    b.HasIndex(new[] { "PackageId" }, "idx_reviews_package_id");

                    b.HasIndex(new[] { "PackagerId" }, "idx_reviews_packager_id");

                    b.HasIndex(new[] { "UserId" }, "idx_reviews_user_id");

                    b.HasIndex(new[] { "BookingId" }, "reviews_booking_id_key")
                        .IsUnique();

                    b.ToTable("reviews", (string)null);
                });

            modelBuilder.Entity("TravelTourManagement.DataAccess.Entities.ReviewMedium", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_path");

                    b.Property<Guid>("ReviewId")
                        .HasColumnType("uuid")
                        .HasColumnName("review_id");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("uploaded_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("review_media_pkey");

                    b.HasIndex(new[] { "ReviewId" }, "idx_review_media_review_id");

                    b.ToTable("review_media", (string)null);
                });

            modelBuilder.Entity("TravelTourManagement.DataAccess.Entities.TravelDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("document_type");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_path");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<string>("MimeType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("mime_type");

                    b.Property<string>("OriginalFilename")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("original_filename");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("rejection_reason");

                    b.Property<DocumentStatus>("Status")
                        .HasColumnType("document_status")
                        .HasColumnName("status");

                    b.Property<Guid?>("TravelerId")
                        .HasColumnType("uuid")
                        .HasColumnName("traveler_id");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("uploaded_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("verified_at");

                    b.Property<Guid?>("VerifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("verified_by");

                    b.HasKey("Id")
                        .HasName("travel_documents_pkey");

                    b.HasIndex("VerifiedBy");

                    b.HasIndex(new[] { "BookingId" }, "idx_docs_booking_id");

                    b.HasIndex(new[] { "TravelerId" }, "idx_docs_traveler_id");

                    b.ToTable("travel_documents", (string)null);
                });

            modelBuilder.Entity("TravelTourManagement.DataAccess.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsEmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_email_verified");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("ProfilePicture")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("profile_picture");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.HasIndex(new[] { "IsActive" }, "idx_users_active");

                    b.HasIndex(new[] { "Email" }, "idx_users_email");

                    b.HasIndex(new[] { "Email" }, "users_email_key")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("TravelTourManagement.DataAccess.Entities.VBookingRevenue", b =>
                {
                    b.Property<int?>("AdultCount")
                        .HasColumnType("integer")
                        .HasColumnName("adult_count");

                    b.Property<DateTime?>("BookedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("booked_at");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<string>("BookingReference")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("booking_reference");

                    b.Property<int?>("ChildCount")
                        .HasColumnType("integer")
                        .HasColumnName("child_count");

                    b.Property<string>("Destination")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("destination");

                    b.Property<Guid?>("PackageId")
                        .HasColumnType("uuid")
                        .HasColumnName("package_id");

                    b.Property<string>("PackageTitle")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("package_title");

                    b.Property<decimal?>("PackagerBaseAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("packager_base_amount");

                    b.Property<Guid?>("PackagerId")
                        .HasColumnType("uuid")
                        .HasColumnName("packager_id");

                    b.Property<string>("PackagerName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("packager_name");

                    b.Property<decimal?>("PaidAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("paid_amount");

                    b.Property<decimal?>("PlatformFeeAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("platform_fee_amount");

                    b.Property<decimal?>("PlatformFeePercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("platform_fee_percent");

                    b.Property<DateOnly?>("ReturnDate")
                        .HasColumnType("date")
                        .HasColumnName("return_date");

                    b.Property<decimal?>("TaxAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("tax_amount");

                    b.Property<decimal?>("TotalAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total_amount");

                    b.Property<DateOnly?>("TravelDate")
                        .HasColumnType("date")
                        .HasColumnName("travel_date");

                    b.Property<string>("UserEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_email");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("UserName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("user_name");

                    b.Property<string>("UserPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("user_phone");

                    b.ToTable((string)null);

                    b.ToView("v_booking_revenue", (string)null);
                });

            modelBuilder.Entity("TravelTourManagement.DataAccess.Entities.VPackagerRevenueSummary", b =>
                {
                    b.Property<long?>("CancelledBookings")
                        .HasColumnType("bigint")
                        .HasColumnName("cancelled_bookings");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("company_name");

                    b.Property<long?>("CompletedBookings")
                        .HasColumnType("bigint")
                        .HasColumnName("completed_bookings");

                    b.Property<long?>("ConfirmedBookings")
                        .HasColumnType("bigint")
                        .HasColumnName("confirmed_bookings");

                    b.Property<Guid?>("PackagerId")
                        .HasColumnType("uuid")
                        .HasColumnName("packager_id");

                    b.Property<long?>("TotalBookings")
                        .HasColumnType("bigint")
                        .HasColumnName("total_bookings");

                    b.Property<decimal?>("TotalEarned")
                        .HasColumnType("numeric")
                        .HasColumnName("total_earned");

                    b.Property<decimal?>("TotalGmv")
                        .HasColumnType("numeric")
                        .HasColumnName("total_gmv");

                    b.Property<decimal?>("TotalPlatformFee")
                        .HasColumnType("numeric")
                        .HasColumnName("total_platform_fee");

                    b.ToTable((string)null);

                    b.ToView("v_packager_revenue_summary", (string)null);
                });

            modelBuilder.Entity("TravelTourManagement.DataAccess.Entities.Wishlist", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uuid")
                        .HasColumnName("package_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("wishlists_pkey");

                    b.HasIndex("PackageId");

                    b.HasIndex("UserId", "PackageId")
                        .IsUnique()
                        .HasDatabaseName("ix_wishlists_user_id_package_id");

                    b.ToTable("wishlists", (string)null);
                });

            modelBuilder.Entity("TravelTourManagement.DataAccess.Entities.AuditLog", b =>
                {
                    b.HasOne("TravelTourManagement.DataAccess.Entities.User", "PerformedByNavigation")
                        .WithMany("AuditLogs")
                        .HasForeignKey("PerformedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("audit_logs_performed_by_fkey");

                    b.Navigation("PerformedByNavigation");
                });

            modelBuilder.Entity("TravelTourManagement.DataAccess.Entities.Booking", b =>
                {
                    b.HasOne("TravelTourManagement.DataAccess.Entities.Package", "Package")
                        .WithMany("Bookings")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("bookings_package_id_fkey");

                    b.HasOne("TravelTourManagement.DataAccess.Entities.PackageSeasonalPricing", "SeasonalPricing")
                        .WithMany("Bookings")
                        .HasForeignKey("SeasonalPricingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("bookings_seasonal_pricing_id_fkey");

                    b.HasOne("TravelTourManagement.DataAccess.Entities.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("bookings_user_id_fkey");

                    b.Navigation("Package");

                    b.Navigation("SeasonalPricing");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TravelTourManagement.DataAccess.Entities.BookingTraveler", b =>
                {
                    b.HasOne("TravelTourManagement.DataAccess.Entities.Booking", "Booking")
                        .WithMany("BookingTravelers")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("booking_travelers_booking_id_fkey");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("TravelTourManagement.DataAccess.Entities.ItineraryActivity", b =>
                {
                    b.HasOne("TravelTourManagement.DataAccess.Entities.ItineraryDay", "ItineraryDay")
                        .WithMany("ItineraryActivities")
                        .HasForeignKey("ItineraryDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("itinerary_activities_itinerary_day_id_fkey");

                    b.Navigation("ItineraryDay");
                });

            modelBuilder.Entity("TravelTourManagement.DataAccess.Entities.ItineraryDay", b =>
                {
                    b.HasOne("TravelTourManagement.DataAccess.Entities.Package", "Package")
                        .WithMany("ItineraryDays")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("itinerary_days_package_id_fkey");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("TravelTourManagement.DataAccess.Entities.ItineraryDayMeal", b =>
                {
                    b.HasOne("TravelTourManagement.DataAccess.Entities.ItineraryDay", "ItineraryDay")
                        .WithMany("ItineraryDayMeals")
                        .HasForeignKey("ItineraryDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("itinerary_day_meals_itinerary_day_id_fkey");

                    b.Navigation("ItineraryDay");
                });

            modelBuilder.Entity("TravelTourManagement.DataAccess.Entities.Message", b =>
                {
                    b.HasOne("TravelTourManagement.DataAccess.Entities.User", "Sender")
                        .WithMany("Messages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("messages_sender_id_fkey");

                    b.HasOne("TravelTourManagement.DataAccess.Entities.MessageThread", "Thread")
                        .WithMany("Messages")
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("messages_thread_id_fkey");

                    b.Navigation("Sender");

                    b.Navigation("Thread");
                });

            modelBuilder.Entity("TravelTourManagement.DataAccess.Entities.MessageThread", b =>
                {
                    b.HasOne("TravelTourManagement.DataAccess.Entities.Package", "Package")
                        .WithMany("MessageThreads")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("message_threads_package_id_fkey");

                    b.HasOne("TravelTourManagement.DataAccess.Entities.Packager", "Packager")
                        .WithMany("MessageThreads")
                        .HasForeignKey("PackagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("message_threads_packager_id_fkey");

                    b.HasOne("TravelTourManagement.DataAccess.Entities.User", "User")
                        .WithMany("MessageThreads")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("message_threads_user_id_fkey");

                    b.Navigation("Package");

                    b.Navigation("Packager");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TravelTourManagement.DataAccess.Entities.Notification", b =>
                {
                    b.HasOne("TravelTourManagement.DataAccess.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("notifications_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TravelTourManagement.DataAccess.Entities.Package", b =>
                {
                    b.HasOne("TravelTourManagement.DataAccess.Entities.Packager", "Packager")
                        .WithMany("Packages")
                        .HasForeignKey("PackagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("packages_packager_id_fkey");

                    b.Navigation("Packager");
                });

            modelBuilder.Entity("TravelTourManagement.DataAccess.Entities.PackageAccommodation", b =>
                {
                    b.HasOne("TravelTourManagement.DataAccess.Entities.ItineraryDay", "ItineraryDay")
                        .WithMany("PackageAccommodations")
                        .HasForeignKey("ItineraryDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("package_accommodation_itinerary_day_id_fkey");

                    b.Navigation("ItineraryDay");
                });

            modelBuilder.Entity("TravelTourManagement.DataAccess.Entities.PackageHighlight", b =>
                {
                    b.HasOne("TravelTourManagement.DataAccess.Entities.Package", "Package")
                        .WithMany("PackageHighlights")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("package_highlights_package_id_fkey");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("TravelTourManagement.DataAccess.Entities.PackageInclusion", b =>
                {
                    b.HasOne("TravelTourManagement.DataAccess.Entities.Package", "Package")
                        .WithMany("PackageInclusions")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("package_inclusions_package_id_fkey");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("TravelTourManagement.DataAccess.Entities.PackageMedium", b =>
                {
                    b.HasOne("TravelTourManagement.DataAccess.Entities.Package", "Package")
                        .WithMany("PackageMedia")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("package_media_package_id_fkey");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("TravelTourManagement.DataAccess.Entities.PackageSeasonalPricing", b =>
                {
                    b.HasOne("TravelTourManagement.DataAccess.Entities.Package", "Package")
                        .WithMany("PackageSeasonalPricings")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("package_seasonal_pricing_package_id_fkey");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("TravelTourManagement.DataAccess.Entities.PackageTransport", b =>
                {
                    b.HasOne("TravelTourManagement.DataAccess.Entities.ItineraryDay", "ItineraryDay")
                        .WithMany("PackageTransports")
                        .HasForeignKey("ItineraryDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("package_transport_itinerary_day_id_fkey");

                    b.Navigation("ItineraryDay");
                });

            modelBuilder.Entity("TravelTourManagement.DataAccess.Entities.Packager", b =>
                {
                    b.HasOne("TravelTourManagement.DataAccess.Entities.User", "ApprovedByNavigation")
                        .WithMany("PackagerApprovedByNavigations")
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("packagers_approved_by_fkey");

                    b.HasOne("TravelTourManagement.DataAccess.Entities.User", "User")
                        .WithOne("PackagerUser")
                        .HasForeignKey("TravelTourManagement.DataAccess.Entities.Packager", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("packagers_user_id_fkey");

                    b.Navigation("ApprovedByNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TravelTourManagement.DataAccess.Entities.Payment", b =>
                {
                    b.HasOne("TravelTourManagement.DataAccess.Entities.Booking", "Booking")
                        .WithMany("Payments")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("payments_booking_id_fkey");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("TravelTourManagement.DataAccess.Entities.PlatformConfig", b =>
                {
                    b.HasOne("TravelTourManagement.DataAccess.Entities.User", "UpdatedByNavigation")
                        .WithMany("PlatformConfigs")
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("platform_config_updated_by_fkey");

                    b.Navigation("UpdatedByNavigation");
                });

            modelBuilder.Entity("TravelTourManagement.DataAccess.Entities.Review", b =>
                {
                    b.HasOne("TravelTourManagement.DataAccess.Entities.Booking", "Booking")
                        .WithOne("Review")
                        .HasForeignKey("TravelTourManagement.DataAccess.Entities.Review", "BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("reviews_booking_id_fkey");

                    b.HasOne("TravelTourManagement.DataAccess.Entities.Package", "Package")
                        .WithMany("Reviews")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("reviews_package_id_fkey");

                    b.HasOne("TravelTourManagement.DataAccess.Entities.Packager", "Packager")
                        .WithMany("Reviews")
                        .HasForeignKey("PackagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("reviews_packager_id_fkey");

                    b.HasOne("TravelTourManagement.DataAccess.Entities.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("reviews_user_id_fkey");

                    b.Navigation("Booking");

                    b.Navigation("Package");

                    b.Navigation("Packager");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TravelTourManagement.DataAccess.Entities.ReviewMedium", b =>
                {
                    b.HasOne("TravelTourManagement.DataAccess.Entities.Review", "Review")
                        .WithMany("ReviewMedia")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("review_media_review_id_fkey");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("TravelTourManagement.DataAccess.Entities.TravelDocument", b =>
                {
                    b.HasOne("TravelTourManagement.DataAccess.Entities.Booking", "Booking")
                        .WithMany("TravelDocuments")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("travel_documents_booking_id_fkey");

                    b.HasOne("TravelTourManagement.DataAccess.Entities.BookingTraveler", "Traveler")
                        .WithMany("TravelDocuments")
                        .HasForeignKey("TravelerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("travel_documents_traveler_id_fkey");

                    b.HasOne("TravelTourManagement.DataAccess.Entities.User", "VerifiedByNavigation")
                        .WithMany("TravelDocuments")
                        .HasForeignKey("VerifiedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("travel_documents_verified_by_fkey");

                    b.Navigation("Booking");

                    b.Navigation("Traveler");

                    b.Navigation("VerifiedByNavigation");
                });

            modelBuilder.Entity("TravelTourManagement.DataAccess.Entities.Wishlist", b =>
                {
                    b.HasOne("TravelTourManagement.DataAccess.Entities.Package", "Package")
                        .WithMany("Wishlists")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("wishlists_package_id_fkey");

                    b.HasOne("TravelTourManagement.DataAccess.Entities.User", "User")
                        .WithMany("Wishlists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("wishlists_user_id_fkey");

                    b.Navigation("Package");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TravelTourManagement.DataAccess.Entities.Booking", b =>
                {
                    b.Navigation("BookingTravelers");

                    b.Navigation("Payments");

                    b.Navigation("Review");

                    b.Navigation("TravelDocuments");
                });

            modelBuilder.Entity("TravelTourManagement.DataAccess.Entities.BookingTraveler", b =>
                {
                    b.Navigation("TravelDocuments");
                });

            modelBuilder.Entity("TravelTourManagement.DataAccess.Entities.ItineraryDay", b =>
                {
                    b.Navigation("ItineraryActivities");

                    b.Navigation("ItineraryDayMeals");

                    b.Navigation("PackageAccommodations");

                    b.Navigation("PackageTransports");
                });

            modelBuilder.Entity("TravelTourManagement.DataAccess.Entities.MessageThread", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("TravelTourManagement.DataAccess.Entities.Package", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("ItineraryDays");

                    b.Navigation("MessageThreads");

                    b.Navigation("PackageHighlights");

                    b.Navigation("PackageInclusions");

                    b.Navigation("PackageMedia");

                    b.Navigation("PackageSeasonalPricings");

                    b.Navigation("Reviews");

                    b.Navigation("Wishlists");
                });

            modelBuilder.Entity("TravelTourManagement.DataAccess.Entities.PackageSeasonalPricing", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("TravelTourManagement.DataAccess.Entities.Packager", b =>
                {
                    b.Navigation("MessageThreads");

                    b.Navigation("Packages");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("TravelTourManagement.DataAccess.Entities.Review", b =>
                {
                    b.Navigation("ReviewMedia");
                });

            modelBuilder.Entity("TravelTourManagement.DataAccess.Entities.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Bookings");

                    b.Navigation("MessageThreads");

                    b.Navigation("Messages");

                    b.Navigation("Notifications");

                    b.Navigation("PackagerApprovedByNavigations");

                    b.Navigation("PackagerUser");

                    b.Navigation("PlatformConfigs");

                    b.Navigation("Reviews");

                    b.Navigation("TravelDocuments");

                    b.Navigation("Wishlists");
                });
#pragma warning restore 612, 618
        }
    }
}
